# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  
  config.vm.box = "docear_debian_squeeze_v2"
  config.vm.box_url = "http://downloads.docear.org/distribute/vagrant-box/docear_debian_squeeze_v2.box"
  
  config.vm.forward_port 80, 5080
end
